//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemanApotikProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harga
    {
        public int id_Harga { get; set; }
        public Nullable<int> id_Obat { get; set; }
        public Nullable<int> id_Jenis_Obat { get; set; }
        public Nullable<int> Harga_Awal { get; set; }
        public Nullable<int> Diskon { get; set; }
        public Nullable<int> Harga_Akhir { get; set; }
    
        public virtual Obat Obat { get; set; }
    }
}
