//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemanApotikProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obat()
        {
            this.Hargas = new HashSet<Harga>();
            this.ObatKeluars = new HashSet<ObatKeluar>();
            this.ObatMasuks = new HashSet<ObatMasuk>();
            this.StokObats = new HashSet<StokObat>();
        }
    
        public int id_Obat { get; set; }
        public string Kode_Obat { get; set; }
        public string Nama_Obat { get; set; }
        public Nullable<int> id_Jenis_Obat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Harga> Hargas { get; set; }
        public virtual JenisObat JenisObat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObatKeluar> ObatKeluars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObatMasuk> ObatMasuks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokObat> StokObats { get; set; }
    }
}
