//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemanApotikProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObatMasuk
    {
        public int id_Transaksi_Masuk { get; set; }
        public Nullable<System.DateTime> Tgl_Masuk { get; set; }
        public Nullable<int> id_Supplier { get; set; }
        public Nullable<int> id_Obat { get; set; }
        public Nullable<int> id_Jenis_Obat { get; set; }
        public Nullable<int> Jumlah_Masuk { get; set; }
        public Nullable<int> Harga_Beli { get; set; }
    
        public virtual Obat Obat { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
