//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemanApotikProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pasien()
        {
            this.ObatKeluars = new HashSet<ObatKeluar>();
        }
    
        public int id_Pasien { get; set; }
        public string Nama_Pasien { get; set; }
        public string Alamat_Pasien { get; set; }
        public string Diagnosa_Penyakit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObatKeluar> ObatKeluars { get; set; }
    }
}
