//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemanApotikProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TemanApotikEntities : DbContext
    {
        public TemanApotikEntities()
            : base("name=TemanApotikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Harga> Hargas { get; set; }
        public virtual DbSet<JenisObat> JenisObats { get; set; }
        public virtual DbSet<Obat> Obats { get; set; }
        public virtual DbSet<ObatKeluar> ObatKeluars { get; set; }
        public virtual DbSet<ObatMasuk> ObatMasuks { get; set; }
        public virtual DbSet<Pasien> Pasiens { get; set; }
        public virtual DbSet<StokObat> StokObats { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
